name=input("enter your name ")
place1=input("pick a place ")
food1=input("pick a food ")
food2=input("pick a second food ")
ad=input("pick an adverb ")
Verb=input("name a verb ")
noun=input("give me a noun ")
adj1=input("give me an adjective ")
adj2=input("give me another adjective ")
print("\n")
print("Let's play silly sentences! ")
print(name + " was planning a vacation to " + place1)
print(name + " was especially looking forward to trying the local cusine, including " + adj1 + food1 + "and " + food2)
print("\n")
print(name + " will have to practice the language " + ad +" to make it easier to "+ Verb + " with people " )
print("\n")
print(name + " has a long list of sights to see, including the " + noun + " museum and the " + adj2 + " park.")